name: recrutement
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  buttons_tabbar: ^1.1.0 
  file_picker: ^8.0.0+1
  dio: ^5.0.4
  http: ^1.2.2
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  accordion: ^2.6.0
  flutter_form_builder: ^9.3.0
  form_builder_validators: ^11.0.0
  pdf: ^3.11.1
  path_provider: ^2.1.4
  table_calendar: ^3.1.2



  intl: any
  flutter_localization: ^0.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  freezed: ^2.5.2
  json_serializable: ^6.8.0



flutter:
  uses-material-design: true
 
      

  assets:
    - assets/logoo.png
    - assets/Background.jpg
    - assets/oo.jpg
    - assets/poi.jpg
    - assets/test.jpg
    - assets/icons/
    - assets/mm.jpg
    - assets/nn.jpg
    - assets/lol.jpg
    - assets/logoBlanc.jpg
    - assets/BlancLogo.png
    
    